import type { typeTitles } from "../types/types";



export const HOST: string = 'https://kunlun.imhcg.cn'

export const TITLES: Partial<typeTitles> = {
  hostname: ['主机名', '', '当前服务器的主机名称'],
  uptime_days: ['运行时间', '天', '服务器自上次启动以来的运行天数'],
  tasks_info: ['进程 (运行中/全部)', '', '当前运行的进程数量与总进程数量'],
  load_averages_info: ['负载', '', '系统在过去 1、5、15 分钟的平均负载'],
  memory_usage_el: ['内存', '', '当前内存使用情况，已用/总容量'],
  traffic_info: ['总流量 (接收/发送)', 'G', '服务器自上次启动以来的网络总流量，包括接收和发送的数据量'],
  connection_info: ['连接数 (TCP/UDP)', '', '当前 TCP 和 UDP 连接数'],
  net_tx_speed_kib: ['上传速度', 'K', '当前网络上传速度'],
  net_rx_speed_kib: ['下载速度', 'K', '当前网络下载速度'],
  update_at: ['更新时间', '', '数据最后更新时间'],
  cpu_num_cores: ['CPU 核心数', '', 'CPU 的核心数量'],
  cpu_delay_us: ['CPU 延迟', 'μs', 'CPU 处理任务的延迟时间'],
  cpu_us_percent: ['CPU 用户占用', '%', '用户进程占用的 CPU 百分比'],
  cpu_sy_percent: ['CPU 系统占用', '%', '系统内核占用的 CPU 百分比'],
  cpu_ni_percent: ['CPU 低优先级', '%', '低优先级进程占用的 CPU 百分比'],
  cpu_id_percent: ['CPU 空闲', '%', 'CPU 空闲时间的百分比'],
  cpu_wa_percent: ['CPU IO等待', '%', 'CPU 等待 I/O 操作的时间百分比'],
  cpu_hi_percent: ['CPU 硬件中断', '%', '硬件中断占用的 CPU 百分比'],
  cpu_st_percent: ['CPU 被宿主机占用', '%', '虚拟机被宿主机占用的 CPU 百分比'],
  root_disk_useage_el: ['根目录空间', '', '根目录磁盘的使用情况，已用/总容量%'],
  disk_delay_us: ['磁盘延迟', 'ms', '根目录磁盘 I/O 操作的延迟时间'],
  disk_reads_per_second: ['读取次数', '', '根目录磁盘采样周期内的读取操作次数'],
  disk_writes_per_second: ['写入次数', '', '根目录磁盘采样周期内的写入操作次数'],
  disk_avg_read_latency: ['平均读取延迟', 'ms', '根目录磁盘读取操作的平均延迟时间'],
  disk_avg_write_latency: ['平均写入延迟', 'ms', '根目录磁盘写入操作的平均延迟时间'],
  disk_utilization: ['磁盘利用率', '%', '根目录磁盘的使用率百分比'],
  disk_weighted_iotime_percent: ['加权I/O时间', '%', '根目录磁盘 I/O 操作的加权时间百分比'],
};


export const historicalTitles: Partial<typeTitles> = {
  uptime_s: ["运行时间", "秒", "系统运行的总时间（秒）"],
  load_1min: ["负载-1分钟", "", "过去1分钟的系统平均负载"],
  load_5min: ["负载-5分钟负载", "", "过去5分钟的系统平均负载"],
  load_15min: ["负载-15分钟负载", "", "过去15分钟的系统平均负载"],
  running_tasks: ["任务数-正在进行", "", "当前正在运行的任务数量"],
  total_tasks: ["任务数-全部", "", "系统中总的任务数量"],
  cpu_num_cores: ["CPU-核心数", "", "CPU的核心数量"],
  cpu_delay_us: ["CPU-延迟", "μs", "CPU任务的延迟时间（微秒）"],
  cpu_user: ["CPU-用户占用", "%", "用户空间占用的CPU百分比"],
  cpu_system: ["CPU-系统占用", "%", "内核空间占用的CPU百分比"],
  cpu_nice: ["CPU-低优先级", "%", "低优先级进程占用的CPU百分比"],
  cpu_idle: ["CPU-空闲", "%", "CPU空闲时间的百分比"],
  cpu_iowait: ["CPU-IO等待", "%", "CPU等待IO操作的时间百分比"],
  cpu_irq: ["CPU-硬件中断", "%", "CPU处理硬中断的时间百分比"],
  cpu_softirq: ["CPU-软件中断", "%", "CPU处理软中断的时间百分比"],
  cpu_steal: ["CPU-被宿主机占用", "%", "虚拟CPU等待物理CPU的时间百分比"],
  mem_really_used_mib: ["内存-真实已用", "Mib", "减去缓存和缓冲的内存占用大小（MiB）"],
  mem_used_total_percent: ["内存-已用占比", "%", "真实内存使用量占比"],
  mem_total_mib: ["内存-全部", "MiB", "系统总内存大小（MiB）"],
  mem_free_mib: ["内存-空闲", "MiB", "系统空闲内存大小（MiB）"],
  mem_used_mib: ["内存-已用", "MiB", "系统已用内存大小（MiB）"],
  mem_buff_cache_mib: ["内存-缓存", "MiB", "用于缓存和缓冲的内存大小（MiB）"],
  tcp_connections: ["连接数-TCP", "个", "当前TCP连接数量"],
  udp_connections: ["连接数-UDP", "个", "当前UDP连接数量"],
  default_interface_net_rx_bytes: ["流量-下载速度", "Bit", "当前开机期间默认网络接口接收的总字节数"],
  default_interface_net_tx_bytes: ["流量-上传速度", "Bit", "当前开机期间默认网络接口发送的总字节数"],
  disk_delay_us: ["磁盘-延迟", "ms", "磁盘IO操作的延迟时间（毫秒）"],
  root_disk_total_kb: ["磁盘-根目录总空间", "KB", "根磁盘的总容量（KB）"],
  root_disk_avail_kb: ["磁盘-根目录可用空间", "KB", "根磁盘的可用容量（KB）"],
  reads_completed: ["磁盘-读取完成次数", "", "磁盘读取操作完成的次数"],
  writes_completed: ["磁盘-写入完成次数", "", "磁盘写入操作完成的次数"],
  reading_ms: ["磁盘-读取时间", "ms", "磁盘读取操作的总时间（毫秒）"],
  writing_ms: ["磁盘-写入时间", "ms", "磁盘写入操作的总时间（毫秒）"],
  iotime_ms: ["磁盘-IO时间", "ms", "磁盘IO操作的总时间（毫秒）"],
  ios_in_progress: ["磁盘-进行中的IO操作", "", "当前正在进行的磁盘IO操作数量"],
  weighted_io_time: ["磁盘-加权IO时间", "ms", "加权后的磁盘IO操作时间（毫秒）"],
};